# Generated by Django 6.0 on 2025-12-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Sócio Clube Mandala', max_length=100)),
                ('subtitulo', models.CharField(help_text='Ex: Para quem já é sócio', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beneficios', models.TextField(help_text='Coloque um benefício por linha')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores/')),
                ('descricao', models.TextField(help_text='Uma breve apresentação do professor')),
            ],
        ),
    ]
