# Generated by Django 6.0 on 2025-12-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_nascimento', models.IntegerField(help_text='Ex: 2015')),
                ('observacoes', models.TextField(blank=True, help_text='Posição, alergias, etc.', null=True)),
            ],
        ),
    ]
