# Generated by Django 6.0 on 2025-12-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0002_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel. do Responsável'),
        ),
    ]
