# Generated by Django 6.0 on 2025-12-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0003_aluno_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='periodo',
            field=models.CharField(choices=[('/mês', '/mês'), ('/aula', '/aula'), ('/hora', '/hora'), ('/ano', '/ano')], default='/mês', max_length=20, verbose_name='Cobrança'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='beneficios',
            field=models.TextField(help_text='Separe os itens por quebra de linha'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
