# Generated by Django 6.0 on 2025-12-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolinha', '0004_plano_periodo_alter_plano_beneficios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Sub-11 Manhã', max_length=50)),
                ('horario', models.CharField(help_text='Ex: 08:00 às 10:00', max_length=50)),
                ('dias', models.CharField(help_text='Ex: Terças e Quintas', max_length=50)),
            ],
        ),
    ]
